In [7]:
import os
import numpy as np


def read_file(path):
    seq = []
    for line in open(path):
        line=line.strip('\n')
        seq.append(float(line))
    return seq[-1]

In [8]:
object_list = os.listdir('../evals')
object_list.sort()
IP_list = []
GP_list = []
for object in object_list:
    IP_list.append(str('../evals/' + object + '/IP.txt'))
    GP_list.append(str('../evals/' + object + '/GP.txt'))

In [9]:
object_IP = []
object_GP = []
for IP in IP_list:
    object_IP.append(read_file(IP))
for GP in GP_list:
    object_GP.append(read_file(GP))
object_IP = np.array(object_IP)
object_GP = np.array(object_GP)

In [10]:
object_IP

array([0.7027027 , 0.88235294, 0.96153846, 0.90625   , 0.80645161,
       0.875     , 0.71428571, 0.74193548, 0.63888889, 0.61290323,
       0.75      , 0.94117647, 0.88888889, 0.55555556, 0.84615385,
       0.96875   ])

In [11]:
object_GP

array([0.67567568, 0.85294118, 0.86538462, 0.75      , 0.67741935,
       0.625     , 0.68571429, 0.74193548, 0.55555556, 0.58064516,
       0.75      , 0.91176471, 0.66666667, 0.55555556, 0.73076923,
       0.78125   ])

In [12]:
IPGP = np.zeros(32)
for i in range(32):
    if i % 2 == 0:
        idx = int(i/2)
        IPGP[i] = object_IP[idx]
    else:
        idx = int((i-1)/2)
        IPGP[i] = object_GP[idx]
IPGP

array([0.7027027 , 0.67567568, 0.88235294, 0.85294118, 0.96153846,
       0.86538462, 0.90625   , 0.75      , 0.80645161, 0.67741935,
       0.875     , 0.625     , 0.71428571, 0.68571429, 0.74193548,
       0.74193548, 0.63888889, 0.55555556, 0.61290323, 0.58064516,
       0.75      , 0.75      , 0.94117647, 0.91176471, 0.88888889,
       0.66666667, 0.55555556, 0.55555556, 0.84615385, 0.73076923,
       0.96875   , 0.78125   ])