In [206]:
import os
import numpy as np


def read_file(path):
    seq = []
    for line in open(path):
        line=line.strip('\n')
        seq.append(float(line))
    return seq[-1]

In [207]:
object_list = os.listdir('../evals')
object_list.sort()
IP_list = []
GP_list = []
for object in object_list:
    IP_list.append(str('../evals/' + object + '/IP.txt'))
    GP_list.append(str('../evals/' + object + '/GP.txt'))

In [208]:
object_IP = []
object_GP = []
for IP in IP_list:
    object_IP.append(read_file(IP))
for GP in GP_list:
    object_GP.append(read_file(GP))
object_IP = np.array(object_IP)
object_GP = np.array(object_GP)

In [209]:
object_IP

array([0.83783784, 0.97058824, 0.84615385, 0.78125   , 0.87096774,
       0.91666667, 0.74285714, 0.70967742, 0.58333333, 0.38709677,
       0.86111111, 0.97058824, 0.83333333, 0.42592593, 0.65384615,
       0.90625   ])

In [210]:
object_GP

array([0.67567568, 0.58823529, 0.40384615, 0.46875   , 0.51612903,
       0.54166667, 0.62857143, 0.4516129 , 0.36111111, 0.32258065,
       0.58333333, 0.5       , 0.27777778, 0.27777778, 0.42307692,
       0.34375   ])

In [211]:
IPGP = np.zeros(32)
for i in range(32):
    if i % 2 == 0:
        idx = int(i/2)
        IPGP[i] = object_IP[idx]
    else:
        idx = int((i-1)/2)
        IPGP[i] = object_GP[idx]
IPGP

array([0.83783784, 0.67567568, 0.97058824, 0.58823529, 0.84615385,
       0.40384615, 0.78125   , 0.46875   , 0.87096774, 0.51612903,
       0.91666667, 0.54166667, 0.74285714, 0.62857143, 0.70967742,
       0.4516129 , 0.58333333, 0.36111111, 0.38709677, 0.32258065,
       0.86111111, 0.58333333, 0.97058824, 0.5       , 0.83333333,
       0.27777778, 0.42592593, 0.27777778, 0.65384615, 0.42307692,
       0.90625   , 0.34375   ])