In [3]:
import pandas as pd
import numpy as np


def conf(seq):
    p = 0
    for i in seq:
        if i > 0:
            p += i
    return p / len(seq)

def conf_seq(df):
    object_list = df.columns[1:]
    object_seq = []
    for object in object_list:
        object_seq.append(conf(df[object]))
    return object_seq

df1 = pd.read_excel('../results/data.xlsx', sheet_name='score_-c')
df2 = pd.read_excel('../results/data.xlsx', sheet_name='score_b')
df3 = pd.read_excel('../results/data.xlsx', sheet_name='score_b&c')
object_seq1 = conf_seq(df1)
object_seq2 = conf_seq(df2)
object_seq3 = conf_seq(df3)
object_seq1 = np.array(object_seq1)
object_seq1


array([[0.14275416, 0.26463322, 0.08163218, 0.16122796, 0.22358546,
        0.2339215 , 0.13084907, 0.08124185, 0.03303189, 0.06647819,
        0.15675067, 0.32565514, 0.2406247 , 0.01050899, 0.10540369,
        0.15455829]])

In [4]:
object_seq2 = np.array(object_seq2)
object_seq2

array([0.17379272, 0.32873784, 0.27903479, 0.20239387, 0.24587308,
       0.26765333, 0.17690099, 0.13103781, 0.048841  , 0.08043514,
       0.17138952, 0.40101459, 0.29836922, 0.00430622, 0.11671903,
       0.29221358])

In [5]:
object_seq3 = np.array(object_seq3)
object_seq3

array([0.24346973, 0.42765541, 0.3334521 , 0.31097033, 0.34535187,
       0.39326106, 0.28170091, 0.16912615, 0.12303259, 0.14899269,
       0.26795007, 0.48967478, 0.37589441, 0.02763143, 0.23100769,
       0.37590442])